image:
  file: .gitpod.Dockerfile

tasks:
  - name: Application Server
    init: |
      echo 🐧 GitPod Tasks -> Backend -> Init
      ./gradlew build
      echo 🐧 GitPod Tasks -> Backend -> Init done
    command: |
      echo 🐧 GitPod Tasks -> Backend -> Command
      ./gradlew run
      echo 🐧 GitPod Tasks -> Backend -> Command done

ports:
  - port: 8080
#onOpen: open-preview # do not open preview, because there is nothing served on /
vscode:
  extensions:
    #- mathiasfrohlich.Kotlin@1.7.1 # Basic Kotlin extension
    - fwcd.kotlin # Advanced Kotlin extension
    # code completion for application.yml (see: https://docs.micronaut.io/latest/guide/index.html#vsCodeSetup)
    - Pivotal.vscode-spring-boot
