name: "Build checking GraalVM native-image"

on:
  push:
    branches:
      - "master"
      - "github-actions"
      - "feature-graalvm"
  pull_request:
    branches:
      - "master"
      - "github-actions"
      - "feature-graalvm"

permissions:
  contents: read

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false  # Continue other jobs if one failed
      matrix:
        os: [ 'ubuntu-latest' ]  # 'windows-latest' fails
        java-version: [ '17' ]
        graal-version: [ '21.3.3', '22.0.0', '22.1.0', '22.2.0', 'latest', 'dev' ]
    
    runs-on: ${{ matrix.os }}

    timeout-minutes: 360  # Maximum job execution time (as of 2022-07-18)

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
        
      - name: free -m
        run: free -m

      - name: Check out repository
        uses: actions/checkout@v3

      - name: free -m
        run: free -m

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal-version }}
          java-version: ${{ matrix.java-version }}
          components: 'native-image'

      - name: free -m
        run: free -m

      - name: Build native image
        run: ./gradlew nativeCompile

      - name: free -m
        run: free -m

  test:
    name: Test

    strategy:
      fail-fast: false  # Continue other jobs if one failed
      matrix:
        os: [ 'ubuntu-latest' ]  # 'windows-latest' fails
        java-version: [ '17' ]
        graal-version: [ '22.2.0', 'latest', 'dev' ]
    
    runs-on: ${{ matrix.os }}

    timeout-minutes: 360  # Maximum job execution time (as of 2022-07-18)

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1

      - name: free -m
        run: free -m

      - name: Check out repository
        uses: actions/checkout@v3

      - name: free -m
        run: free -m

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal-version }}
          java-version: ${{ matrix.java-version }}
          components: 'native-image'

      - name: free -m
        run: free -m

      - name: Test native image
        run: ./gradlew nativeTest

      - name: free -m
        run: free -m