# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: "CI: Gradle (JDK-Matrix)"

on:
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master", "github-actions" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue other jobs if one failed
      matrix:
        java-version: [ '17', '18' ]
        java-distribution: [ 'zulu', 'temurin', 'corretto', 'liberica' ]  # 2022-07-13: 'microsoft' does not yet provide JDK 18 and would break the matrix
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    name: JDK ${{ matrix.java-version }} (${{ matrix.java-distribution }}) on ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
