name: "Security: Anchore Container Scan"

on:
  push:
    branches: [ "master", "github-actions", "feature-graalvm" ]
  pull_request:
    branches: [ "master", "github-actions", "feature-graalvm" ]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read  # for actions/checkout to fetch code
  security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read  # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 

jobs:
  Anchore-Build-Scan:
    name: Anchore Build Scan

    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Run Anchore scan
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"
          acs-report-enable: true
          fail-build: false

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
