# Not sure I really want this action; but it can provide fats feedback on upcoming changes.

name: Test Gradle build configuration with latest Gradle RC
on:
  schedule:
    - cron: 0 0 * * *  # daily
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master", "github-actions" ]

jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: release-candidate
    - name: Gradle dry-run
      run: gradle build --dry-run  # Just test build configuration